---
- name: Run the equivalent of "apt-get update" as a separate step
  apt: update_cache=yes cache_valid_time=84600

- name: install git
  apt: name={{item}} state=present
  with_items:
    - git
    - python-dev
    - python-rpi.gpio
    - python-smbus
    - i2c-tools

- name: download sourcecode
  git:  repo='http://github.com/adafruit/Adafruit-Raspberry-Pi-Python-Code.git' dest=/home/pi/Adafruit-Raspberry-Pi-Python-Code
